#ifndef SCHNELLE_UMLAUTE_EDITOR_CARET_THEME_H
#define SCHNELLE_UMLAUTE_EDITOR_CARET_THEME_H

// Pure helpers for the caret candidate-window theming: colour normalisation,
// flat classicui.conf parse/patch, and the generated fcitx5 theme.conf. Kept
// header-only and side-effect-free (no file or DBus I/O) so they can be unit
// tested without the editor runtime; SettingsModel wraps them with the actual
// file reads/writes. All compositor-agnostic (classicui is fcitx5's own
// renderer).

#include <QLatin1Char>
#include <QMap>
#include <QSet>
#include <QString>
#include <QStringList>

namespace schnelle_umlaute {

// fcitx5 wants #rrggbbaa. The editor passes opaque colours, but QML may
// stringify a colour as #rrggbb or as Qt's alpha-first #aarrggbb, so handle
// both and emit alpha-last. Non-colour strings pass through unchanged.
inline QString normColor(QString c) {
    c = c.trimmed();
    if (!c.startsWith(QLatin1Char('#')))
        return c;
    if (c.length() == 7) // #rrggbb -> opaque
        return c + QStringLiteral("ff");
    if (c.length() == 9) // Qt #aarrggbb -> #rrggbbaa
        return QStringLiteral("#") + c.mid(3, 6) + c.mid(1, 2);
    return c;
}

// Parse a flat (section-less) key=value config, ignoring blank lines,
// comments (#...) and section headers ([...]). Last value for a key wins.
inline QMap<QString, QString> parseFlatIni(const QString &content) {
    QMap<QString, QString> out;
    const auto lines = content.split(QLatin1Char('\n'));
    for (const QString &line : lines) {
        const QString t = line.trimmed();
        if (t.isEmpty() || t.startsWith(QLatin1Char('#')) ||
            t.startsWith(QLatin1Char('[')))
            continue;
        const qsizetype eq = line.indexOf(QLatin1Char('='));
        if (eq <= 0)
            continue;
        out.insert(line.left(eq).trimmed(), line.mid(eq + 1).trimmed());
    }
    return out;
}

// Apply key=value overrides to existing config lines: replace a matching
// "Key=" line in place (preserving every other line, including comments and
// unrelated keys), and append keys that were missing.
inline QStringList applyIniKeys(QStringList lines,
                                const QMap<QString, QString> &kv) {
    QSet<QString> seen;
    for (QString &line : lines) {
        const qsizetype eq = line.indexOf(QLatin1Char('='));
        if (eq <= 0)
            continue;
        const QString key = line.left(eq).trimmed();
        if (kv.contains(key)) {
            line = key + QStringLiteral("=") + kv.value(key);
            seen.insert(key);
        }
    }
    for (auto it = kv.cbegin(); it != kv.cend(); ++it)
        if (!seen.contains(it.key()))
            lines << it.key() + QStringLiteral("=") + it.value();
    return lines;
}

// Build the fcitx5 classicui theme.conf (pure-colour InputPanel theme) from
// the editor palette. Colour roles (verified against classicui theme.h):
//   [InputPanel/Background] Color  = whole panel background  (background)
//   [InputPanel/Background] BorderColor = panel border       (border)
//   NormalColor                    = non-active candidate text (text)
//   HighlightCandidateColor        = active-candidate text     (onHighlight)
//   HighlightColor                 = active highlight/preedit text, kept equal
//                                    to HighlightCandidateColor (onHighlight)
//   HighlightBackgroundColor       = flat active-candidate background
//                                    (highlight); mirrors [InputPanel/Highlight]
//                                    Color, which draws the same box
inline QString generateCaretThemeConf(const QString &background,
                                      const QString &text,
                                      const QString &highlight,
                                      const QString &onHighlight,
                                      const QString &border) {
    return QStringLiteral(
               "[Metadata]\n"
               "Name=Schnelle Umlaute\n"
               "Version=1\n"
               "Author=schnelle-umlaute\n"
               "Description=Caret overlay palette, generated by the editor\n"
               "\n"
               "[InputPanel]\n"
               "NormalColor=%1\n"
               "HighlightCandidateColor=%2\n"
               "HighlightColor=%2\n"
               "HighlightBackgroundColor=%3\n"
               "\n"
               "[InputPanel/TextMargin]\n"
               "Left=8\nRight=8\nTop=4\nBottom=4\n"
               "\n"
               "[InputPanel/ContentMargin]\n"
               "Left=6\nRight=6\nTop=6\nBottom=6\n"
               "\n"
               "[InputPanel/Background]\n"
               "Color=%4\n"
               "BorderColor=%5\n"
               "BorderWidth=1\n"
               "\n"
               "[InputPanel/Highlight]\n"
               "Color=%3\n"
               "BorderWidth=0\n"
               "\n"
               "[InputPanel/Highlight/Margin]\n"
               "Left=4\nRight=4\nTop=2\nBottom=2\n")
        .arg(normColor(text), normColor(onHighlight), normColor(highlight),
             normColor(background), normColor(border));
}

} // namespace schnelle_umlaute

#endif
